import PixelsContract from '../../build/contracts/Pixels.json';
import PixelsBidContract from '../../build/contracts/PixelsBid.json';

import dappConfig from '../dapp-config.json'; // Generated by migrations

const config = {
  provider: {
    http: dappConfig.httpUrl
  },
  contracts: {
    pixels: {
      address: dappConfig.PixelsAddress,
      abi: PixelsContract.abi
    },
    bids: {
      address: dappConfig.PixelsBidAddress,
      abi: PixelsBidContract.abi
    }
  }
}

export default config;