import PixelsContract from '../../build/contracts/Pixels.json';
import PixelsBidContract from '../../build/contracts/PixelsBid.json';

import dappConfig from '../../dapp-config.json'; // Generated by migrations

const config = {
  contracts: {
    pixels: {
      address: dappConfig.PixelsAddress,
      abi: PixelsContract.abi
    },
    bids: {
      address: dappConfig.PixelsBidAddress,
      abi: PixelsBidContract.abi
    }
  },
  networks: [{
    id: 80001,
    enabled: true,
    chainId: '0x13881',
    chainName: 'Polygon Testnet',
    nativeCurrency: {
      symbol: 'MATIC',
      name: 'Matic token',
      decimals: 18,
    },
    rpcUrls: ['https://rpc-mumbai.maticvigil.com/'],
    blockExplorerUrls: ['https://mumbai.polygonscan.com/'],
  }, {
    id: 137,
    name: 'Matic Mainnet',
    symbol: 'MATIC',
    enabled: false
  }, {
    id: 1,
    name: 'ETH Mainnet',
    symbol: 'ETH',
    enabled: false
  }],
  subgraph: {
    url: 'https://api.studio.thegraph.com/query/9304/autopoietic.art/v0.1.0'
  },
  events: {
    url: 'https://pixelworld-2e64c.uc.r.appspot.com'
  },
  // Need a better solution here
  slideshow: {
    subtitle: '<span>Contribute to social</span> experiment.<br /><span>Become a</span> Creator.', // is HTML
    articles: [{ // This goes async from server
      icon: 'about.svg',
      title: 'About',
      body: 'Players collectively draw on a shared canvas by changing the color of individual pixels and thus continuously contribute to the emerging global image. The goal is to illustrate the process of self-organization within a community of random players with the help of blockchain technology.'
    }, {
      icon: 'ownership.svg',
      title: 'Ownership',
      body: 'Each pixel on the canvas is represented by a non-fungible token (NFT) on the Ethereum network. Ownership is stored and transferred based on the ERC-721 standard as most digital art and collectibles. It cannot be taken away or destroyed.'
    }, {
      icon: 'social-dynamic.svg',
      title: 'Social dynamic',
      body: 'Once a player takes ownership of a pixel he or she can control its color, but also auction it to a different player if an agreement between them is reached. The experiment is decentralized and not controlled by any single actor so in theory it cannot be stopped.'
    }]
  }
}

export default config;