import PixelsContract from '../../build/contracts/Pixels.json';
import PixelsBidContract from '../../build/contracts/PixelsBid.json';

import dappConfig from '../../dapp-config.json'; // Generated by migrations

const config = {
  contracts: {
    pixels: {
      address: dappConfig.PixelsAddress,
      abi: PixelsContract.abi
    },
    bids: {
      address: dappConfig.PixelsBidAddress,
      abi: PixelsBidContract.abi
    }
  },
  networks: [{
    id: 80001,
    enabled: true,
    default: true,
    chainId: '0x13881',
    chainName: 'Polygon Testnet',
    nativeCurrency: {
      symbol: 'MATIC',
      name: 'Matic token',
      decimals: 18,
    },
    wsUrls: ['wss://ws-nd-903-651-087.p2pify.com/a8f3fb78161994322c1e6d30d8a9dd15'],
    rpcUrls: ['https://rpc-mumbai.maticvigil.com/'],
    blockExplorerUrls: ['https://mumbai.polygonscan.com/'],
  }, {
    id: 137,
    name: 'Polygon Mainnet',
    symbol: 'MATIC',
    enabled: false
  }, {
    id: 1,
    name: 'ETH Mainnet',
    symbol: 'ETH',
    enabled: false
  }],
  subgraph: {
    url: 'https://api.thegraph.com/subgraphs/name/jernejc/apoietic' //'https://api.studio.thegraph.com/query/9304/autopoietic.art/v0.1.0'
  },
  events: {
    url: 'https://pixelworld-2e64c.uc.r.appspot.com'
  },
  appConfig: {
    canvasElement: 'app',
    defaultMode: 'select',
    gridSize: 12,
    strokeSize: 0.3,
    strokeColor: '#c1c1c1',
    defaultTileColors: ['#168A33','#16912A','#197A21','#169116','#208714'],
    fps: 30
  },
  slideshow: {
    slideActionText: 'Get Started',
    subtitle: '<span>Contribute to a living</span> canvas.<br /><span>Become a</span> Creator.', // is HTML
    articles: [{ // This goes async from server
      icon: 'about.svg',
      title: 'About',
      body: 'Players collectively draw on a shared canvas by changing the color of individual pixels and thus continuously contribute to the emerging global image. The goal is to illustrate the process of self-organization within a community of random players with the help of <a href="https://en.wikipedia.org/wiki/Blockchain" target="_blank">blockchain</a> technology.'
    }, {
      icon: 'ownership.svg',
      title: 'Ownership',
      body: 'Each pixel on the canvas is represented by a non-fungible token (NFT) on the <a href="https://ethereum.org/" target="_blank">Ethereum</a> network. Ownership is stored and transferred based on the <a href="https://eips.ethereum.org/EIPS/eip-721" target="_blank">ERC-721</a> standard as most digital art and collectibles. It cannot be taken away or destroyed.'
    }, {
      icon: 'social-dynamic.svg',
      title: 'Social dynamic',
      body: 'Once a player takes ownership of a pixel he or she can control its color, but also auction it to a different player if an agreement between them is reached. The experiment is decentralized and not controlled by any single actor.'
    }]
  }
}

export default config;